### ISSUE TITLE
Don't use specific gestures in executeScript

### ISSUE THREAD

**Issue by nvdaes** [javidominguez/commandHelper#1]
Testing this add-on, I cannot execute commands after selecting them with down arrow and pressing enter. After seeing code, I have being able to run some commands after doing the following:

1. Raise an exception to identify the error instead of using pass.
2. I've used the following code, which worked for me:

scriptHandler.executeScript(script, gesture)

Thanks

**Comment by javidominguez** [comment]
I already know what the error is. I used the gesture in scriptHandler.executeScript as str but it must be a keyboardHandler.KeyboardInputGesture class, otherwise willSayAllResume fails if the Allow Shallow Read option is enabled in Speak All in the preferences.

    scriptHandler.executeScript(script, g)
  File "scriptHandler.pyc", line 197, in executeScript
  File "scriptHandler.pyc", line 178, in willSayAllResume
AttributeError: 'str' object has no attribute 'wasInSayAll'

Already solved.

**Comment by nvdaes** [comment]
Thanks, then I"ll"close this issue.
